### ISSUE TITLE
Use of 'buildpack' attribute in manifest is deprecated

### ISSUE THREAD

**Issue by tauinger-de** [cloudfoundry-samples/pong_matcher_spring#5]
When deploying the following warning is emitted:
> Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

To rectify this the single line containg "buildpack" has to be replaced with:
```
    buildpacks:
      - java_buildpack
```

**Comment by animatedmax** [comment]
Hi @tauinger-de I just updated the manifest to address this. Thank you.

**Comment by PrasenjitM9** [comment]
buildpack became "buildpacks". 
The singular buildpack field in manifests is deprecated. \
It has been replaced by buildpacks, which is now an array which takes as a value multiple buildpacks.
[https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#buildpack-deprecated](url)
```
buildpacks:
      - buildpack_URL
      - buildpack_URL
```
**Old:**
```
buildpack: 
     - java_buildpack
```
**New:** 
```
buildpacks:        
    - java_buildpack
```
